### PR TITLE
Update to swift 4.2

### PR DESCRIPTION
**Pull request by yoching**
Updated project to swift4 setting by Xcode converter.

### CODE REVIEW

**Comment by acche** [comment]
Still waiting for review?

**Comment by yoching** [comment]
Yes.

**Comment by DivineDominion** [comment]
Sorry for totally overlooking activity here! Are you game for submitting a Swift 4.2 update?

**Comment by yoching** [comment]
@DivineDominion 
I don't have any plans for updating this now.
But I think I can do it if it's necessary😄

**Comment by DivineDominion** [comment]
Would be cool since you have easier access to your branch. Source changes should not be necessary, I think 🤞

**Comment by DivineDominion** [comment]
Thanks a ton!

**Pull request merged**
